language: go
go:
  - 1.9
  - master

go_import_path: github.com/bigpigeon/toyorm

before_install:
  - mysql -e 'CREATE DATABASE toyorm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'CREATE DATABASE toyorm1 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'CREATE DATABASE toyorm2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

  - psql -c 'CREATE DATABASE toyorm;' -U postgres
  - psql -c 'CREATE DATABASE toyorm1;' -U postgres
  - psql -c 'CREATE DATABASE toyorm2;' -U postgres

  - go get -t -v ./...
  - go get -u github.com/client9/misspell/cmd/misspell

script:
  - go vet .
  - diff=$(gofmt -s -d .);if [ -n "$diff" ]; then exit 1; fi;
  - misspell -error .
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic $(go list ./...|grep -v /examples/)

after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - mysql

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
      packages:
      - postgresql-10
      - postgresql-client-10
  env:
    global:
    - PGPORT=5432